### ISSUE TITLE
Cursor does not appear

### ISSUE THREAD

**Issue by valambrou** [tuberry/color-picker#12]
![image](https://user-images.githubusercontent.com/72850802/98813217-85fc5680-242c-11eb-8e7c-789801e2f7bb.png)

When selecting picker instead of the selection cursor, it shows what I have in the image. I guess a wrong path or something for the cursor?
Running on manjaro with gnome 3.38.1

**Comment by tuberry** [comment]
Cannot reproduce it on Arch / gnome-shell 3.38.1. 
The preview cursor icon is offered by gnome-shell upstream since 3.38 so that there shouldn't be any path issues. Could you provide more detailed steps/envs to reproduce or try to reinstall it from e.g.o?

**Comment by valambrou** [comment]
What do you mean by e.g.o? 
Extension is installed through extensions.gnome.org. 
I just click it to enable it and select a color from the screen. 
I've uninstalled it and installed it again with no luck.

**Comment by tuberry** [comment]
Reproduced but I thought it's a manjaro-specific bug. If you run the command in your terminal, you'll get the same image.
```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Screenshot --method org.gnome.Shell.Screenshot.PickColor
```
And it should be reported to Manjaro devs, maybe the icon file is broken when packaging. 
As for this extension, you could install the older version from github to get the expected behavior:
```
git clone https://github.com/tuberry/color-picker.git
cd color-picker && git checkout --track origin/3.36 && make install
```

**Comment by valambrou** [comment]
Thanks a lot Tuberry. I will report it to the manjaro people. I installed the older version and it works fine. 
Thanks for the help, keep up the good work!
