### ISSUE TITLE
Cursor Icon does not appear in PopOS 20.10

### ISSUE THREAD

**Issue by RafaelGoulartB** [tuberry/color-picker#13]
Running:
  - PopOS: 20.10
  - Gnome: 3.38.1

![Screenshot from 2020-11-13 09-53-33](https://user-images.githubusercontent.com/37313088/99074393-713bd200-2596-11eb-99c1-2250dd692a1d.png)

**Comment by valambrou** [comment]
I too had the same problem on Manjaro with gnome 3.38.1

Temporary solution from the owner(it worked for me):

> Reproduced but I thought it's a manjaro-specific bug. If you run the command in your terminal, you'll get the same image.
> 
> ```
> gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Screenshot --method org.gnome.Shell.Screenshot.PickColor
> ```
> 
> And it should be reported to Manjaro devs, maybe the icon file is broken when packaging.
> As for this extension, you could install the older version from github to get the expected behavior:
> 
> ```
> git clone https://github.com/tuberry/color-picker.git
> cd color-picker && git checkout --track origin/3.36 && make install
> ```

**Comment by tuberry** [comment]
Upstream theme stuffs haven't been complied into a binary file (`/usr/share/gnome-shell/gnome-shell-theme.gresource`). I can find `color-pick` in that `gresource` (opening with vim or gedit) on Archlinux but not on Manjaro. I didn't try PopOS but I thought it's the same. They may forget to recompile the stock gnome shell theme when updating.
