### ISSUE TITLE
Color picking stops when Enable Preview is disabled.

### ISSUE THREAD

**Issue by SaucySauce** [tuberry/color-picker#15]
If I uncheck the Enable Preview the color picker doesn't do anything. Enabling the toggle makes the function work again.
GNOME Wayland 3.38.4
Arch Linux.

**Comment by tuberry** [comment]
Cannot reproduce that in the same env.
Try installing it from github to see if it works.

**Comment by SaucySauce** [comment]
Still nothing.

**Comment by SaucySauce** [comment]
https://user-images.githubusercontent.com/38703177/108614375-89b75600-73e9-11eb-8601-0ce149145e08.mp4

**Comment by SaucySauce** [comment]
I had disabled record of the mouse so that's why it doesn't appear for the most part on the video.

**Comment by tuberry** [comment]
run `journalctl -f -o cat /usr/bin/gnome-shell` in termianl and see the output when picking.
And does it happen with Adwaita cursor theme?

**Comment by SaucySauce** [comment]
![Uploading Screenshot from 2021-02-21 03-45-20.png…]()

**Comment by SaucySauce** [comment]
Changing cursor theme makes no difference.

**Comment by tuberry** [comment]
I got it. You should install the GitHub version and logout then login to take effect:
```
git clone https://github.com/tuberry/color-picker.git
cd color-picker && make install
```

**Comment by tuberry** [comment]
Reproduced. Now, it should be fixed. You should install the GitHub version and logout then login to take effect:
```bash
git clone https://github.com/tuberry/color-picker.git
cd color-picker && make install
```

**Comment by SaucySauce** [comment]
Thanks. It works Great.
