### ISSUE TITLE
Feature Request: Make Extension use user selected icon theme

### ISSUE THREAD

**Issue by SaucySauce** [tuberry/color-picker#16]
Make the Extension use a system/user installed icon theme, like the palette-symbolic

**Comment by tuberry** [comment]
I'd like to use a system icon instead of the current one, provided it is available on all systems. However, `palette-symbolic` is not found in my machine.

**Comment by SaucySauce** [comment]
oh, probably my bad, I'm using Newaita icon theme which has it.

**Comment by tuberry** [comment]
I noticed that Newaita includes a `color-pick.svg` which overwrite the upstream one. So the preview cursor in your screencast is not expected.
![preview](https://user-images.githubusercontent.com/17917040/108615305-b85f1c00-743d-11eb-81cf-744c652e7c2f.png)

**Comment by SaucySauce** [comment]
I also can't make the DROPPER_ICON = 'any-system-icon'. Knowing the palette icon is theme specific I used any other icon that the system comes with and still nothing.

**Comment by tuberry** [comment]
OK, I will provide an option for custom dropper icon later.

**Comment by SaucySauce** [comment]
Thanks. It looks awesome.
![Screenshot from 2021-02-21 22-28-21](https://user-images.githubusercontent.com/38703177/108642338-1dddf780-7494-11eb-9f93-ccd4be914e06.png)
