### ISSUE TITLE
Feature Request: Add clear button in sub menu.

### ISSUE THREAD

**Issue by SaucySauce** [tuberry/color-picker#18]

**Comment by tuberry** [comment]
What does the button use for?

**Comment by SaucySauce** [comment]
to remove the color values in the list so it doesn't become too big.

or add a time limit to how long each color entry shows in the list.

**Comment by tuberry** [comment]
You can actually set the history size next to the icon, and the history is managed in a similar way to the first-in-first-out queue. I don't think the menu will become too long.
