### ISSUE TITLE
Feature Request: Add copy/don't copy auto color code

### ISSUE THREAD

**Issue by MuhammedTaha02** [tuberry/color-picker#21]

**Comment by tuberry** [comment]
I think it is intuitive to automatically copy to the clipboard. What’s the use case for not copying?

**Comment by MuhammedTaha02** [comment]
> I think it is intuitive to automatically copy to the clipboard. What’s the use case for not copying?

I think the color codes fill the board unnecessarily.

**Comment by tuberry** [comment]
So which place would you suggest for more conveniently caching the color except the clipboard? Or how could the color code be passed to the user except via the clipboard?

**Comment by MuhammedTaha02** [comment]
> So which place would you suggest for more conveniently caching the color except the clipboard? Or how could the color code be passed to the user except via the clipboard?

For example, you can use OSD instead of MSG by default?
OSD is the more logical choice for me.

**Comment by tuberry** [comment]
> For example, you can use OSD instead of MSG by default?
> OSD is the more logical choice for me.

If I understand it correctly, it means that auto-copying is illogical or superfluous even though users later must open the menu then remember or click to copy the color. I think it's not a good feature at least for this extension, which is not a formal application and doesn't have a window for users to edit or do other things. For this case, [gcolor3](https://gitlab.gnome.org/World/gcolor3) maybe a better choice for you.

**Comment by MuhammedTaha02** [comment]
> > For example, you can use OSD instead of MSG by default?
> > OSD is the more logical choice for me.
> 
> If I understand it correctly, it means that auto-copying is illogical or superfluous even though users later must open the menu then remember or click to copy the color. I think it's not a good feature at least for this extension, which is not a formal application and doesn't have a window for users to edit or do other things. For this case, [gcolor3](https://gitlab.gnome.org/World/gcolor3) maybe a better choice for you.

What I mean is adding an option in the menu like 'auto copy color code'. The person who wants to copy the color code. Don't let people who don't want to copy. I think it shouldn't be that hard to do.

**Comment by tuberry** [comment]
The pr #22 should be updated before merging.

**Comment by MuhammedTaha02** [comment]
> The pr #22 should be updated before merging.

This pr is for Turkish translation
