### ISSUE TITLE
How to change cursor?

### ISSUE THREAD

**Issue by Abhinav1217** [tuberry/color-picker#24]
Currently, cursor when I click color-picker on my system is this.
![Screenshot from 2021-05-01 12-39-29](https://user-images.githubusercontent.com/740584/116774454-4ed13e80-aa7a-11eb-8fbc-01a7e6585330.png)

This makes it really hard to figure out which part is pointing to the color I want to choose. Since there is no live feedback like one found on other color picker apps, it makes it really hard from usability point of view. I really wanted to use gnome extension instead of external app for color picker. 

I tried changing the system cursor theme but it didn't change anything.

**Comment by tuberry** [comment]
The icon comes from your icon theme instead of cursor theme.  Anyway, it should be fixed no matter in what icon theme. You can try it from GitHub. :)

**Comment by Abhinav1217** [comment]
This was amazingly fast.  I just installed it from repo, and loving it. 

Thank you very much.
