### ISSUE TITLE
Did latest master break GS 3.38 support?

### ISSUE THREAD

**Issue by SaucySauce** [tuberry/color-picker#26]
The preferences window shows an error but using the shell indicator works fine as well as the color ID notification.

https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension/ Also broke pre 40 compatibility and showed the same bug as your extension.

**Comment by tuberry** [comment]
Yes, the git master branch usually only support the most current stable version of GNOME Shell (it's 40 now). I've tagged `3.38` for GS 3.38:
```
git clone https://github.com/tuberry/color-picker.git
cd color-picker && git checkout 3.38 && make install
```
