### ISSUE TITLE
Wrong icon

### ISSUE THREAD

**Issue by iamludal** [tuberry/color-picker#29]
For some (weird) reasons, whenever I want to pick a color, the displayed icon is this one :

![image](https://user-images.githubusercontent.com/44783088/124394927-d436d080-dd01-11eb-84bd-a48274ba1e26.png)

Which makes it difficult to aim the color I want.

NB : thank you for this extension. Incredibly useful (almost life-saving).

**Comment by tuberry** [comment]
It looks like #24 and seems to have been fixed. Could you try that from GitHub to see if it works (Gnome Shell >= 40)?

**Comment by iamludal** [comment]
Now working as expected, thanks for your help!
