### ISSUE TITLE
Cannot reproduce the screenshot on GNOME extensions

### ISSUE THREAD

**Issue by devhammed** [tuberry/color-picker#3]
Hello there, good work so far for this extension but I cannot reproduce the screenshot you used on the GNOME extensions page...maybe some docs will help.

![https://extensions.gnome.org/extension-data/screenshots/screenshot_3396_hrSreME.png](https://extensions.gnome.org/extension-data/screenshots/screenshot_3396_hrSreME.png)

I am not seeing exactly that here.

**Comment by tuberry** [comment]
It's waiting for reviewing at [E.G.O](https://extensions.gnome.org/review/). You could try the newest from Github. :)

**Comment by devhammed** [comment]
Oh Great, I have installed the GitHub version and it is working as expected.
