### ISSUE TITLE
Weird pointer when picking color (Pop OS)

### ISSUE THREAD

**Issue by dopereff** [tuberry/color-picker#31]
The pointer doesn't look like it should on Pop OS. You can see the screenshot

![alt](https://user-images.githubusercontent.com/92185890/142044149-2ebc4d6b-ead2-4d20-9586-279dcb4fc7a6.png)

**Comment by tuberry** [comment]
It looks like #24 and should be fixed for GNOME Shell 40+. However, the [patch](https://github.com/tuberry/color-picker/commit/2a03d8fd27ff649d2afa594a1e49a3f129b4a90b) did not backport to lower versions. 
This [fork](https://github.com/SaucySauce/color-picker-3.38-extension) should do that for you:
```bash
git clone https://github.com/SaucySauce/color-picker-3.38-extension.git
cd color-picker-3.38-extension && make VERSION=20 install
```

**Comment by SumnanAzadi** [comment]
> It looks like #24 and should be fixed for GNOME Shell 40+. However, the [patch](https://github.com/tuberry/color-picker/commit/2a03d8fd27ff649d2afa594a1e49a3f129b4a90b) did not backport to lower versions. This [fork](https://github.com/SaucySauce/color-picker-3.38-extension) should do that for you:
> 
> ```shell
> git clone https://github.com/SaucySauce/color-picker-3.38-extension.git
> cd color-picker-3.38-extension && make VERSION=20 install
> ```

![image](https://user-images.githubusercontent.com/36268124/143731605-3b3be555-e42b-4a2c-9f88-e1697fe53b55.png)
