### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by AmadeusGraves** [tuberry/color-picker#33]
Hi! I give the spanish tranlation, I tried to push a commit but github not allows me so here you go. Good Extension!
[es_ES.zip](https://github.com/tuberry/color-picker/files/7796320/es_ES.zip)
.

**Comment by tuberry** [comment]
Thanks! Could you try forking this repo, pushing a commit to your branch, and making a pull request? One advantage of this is that you will be listed as a contributor. :)
