### ISSUE TITLE
Color Accuracy?

### ISSUE THREAD

**Issue by ndstate** [tuberry/color-picker#35]
Awesome extension, thank you. One thing I am finding is that this dropper is reporting different hex codes than a browser based color picker (which is correct) and the color is different than what GIMP reports - (GIMP is also correct). Any ideas? Thanks

**Comment by tuberry** [comment]
Sorry for late reply.  :)

Cannot reproduce:

GIMP:

![gimp](https://user-images.githubusercontent.com/17917040/163662501-8a4b4dfd-fcca-48e2-8a44-b91ae3da5cbf.png)

Firefox:

![ff](https://user-images.githubusercontent.com/17917040/163662611-fdb99558-b0c1-429e-931d-d99e4f7d7df5.png)

![cp](https://user-images.githubusercontent.com/17917040/163662615-d6c1adc2-df6b-41dd-8f7b-97e9c64e9920.png)
