### ISSUE TITLE
Feature request: customizable shortcut to replace middle click and right click

### ISSUE THREAD

**Issue by UlyssesZh** [tuberry/color-picker#37]
I just want this feature because my pointing device does not have a middle click binding.

**Comment by tuberry** [comment]
[Menu key](https://en.wikipedia.org/wiki/Menu_key) could do the same as Middle-clicking. 

I am not sure what kind of device you have. For a normal mouse, you can follow the table below to modify the [case](https://github.com/tuberry/color-picker/blob/8b9bc6caff39a4633fbed2e9e36f88a535536490/color-picker%40tuberry/extension.js#L396) accordingly:

<table>
<tr>
	<td>button
	<td>left
	<td>middle
	<td>right
	<td>xbutton1
	<td>xbutton2
<tr>
	<td>code
	<td>1
	<td>2
	<td>3
	<td>8
    <td>9
</table>

**Comment by UlyssesZh** [comment]
> [Menu key](https://en.wikipedia.org/wiki/Menu_key) could do the same as Middle-clicking.

Thank you. That helps.

> I am not sure what kind of device you have.

A Wacom drawing tablet.

**Comment by UlyssesZh** [comment]
I just prefer using keyboard. Using the Menu key is helpful enough although I think it can be better if I can customize it to other keys.

**Comment by tuberry** [comment]
If there is a dedicated menu key on your keyboard, that's great and intuitive!
By the way, Esc can end picking as right-click does.
