### ISSUE TITLE
Addition of Remove option

### ISSUE THREAD

**Issue by satrujit11** [tuberry/color-picker#41]
Thank you for this great extension. It reduce a lot of efforts for me . But I have some suggetion on UI/UX of this extension. If you can implement all of those, it will be great.

s1: Please add a option to delete the  individual color picked, It stays on the menu.  
s2: It would be great if you can add a feature to just pop the color copied to the top if it already exists in the history without creating a new one.

![image](https://user-images.githubusercontent.com/66621875/224562973-3fa02938-e5b2-443d-82ea-a50246059804.png)

Here is a UI image for your reference,
Thank you.

![image](https://user-images.githubusercontent.com/66621875/224564069-e7047aa3-af96-4d71-8a60-3db9c3869347.png)

**Comment by tuberry** [comment]
> s1: Please add a option to delete the individual color picked, It stays on the menu.
s2: It would be great if you can add a feature to just pop the color copied to the top if it already exists in the history without creating a new one.

Most of the use cases of this extension are to pick the color and paste it. History only keeps the last N records just in case (e.g. Persistent mode), there is no privacy risk nor much resource usage, and if history is deleted to keep frequently used colors, you can just add them to the collection (click 😎 to see all collected colors). So a serious history management seems unnecessary.

> Here is a UI image for your reference,

The vscode-style color display certainly looks neater, but the vim-style's color area is larger and also shows the lightness (contrast to the text color).
