### ISSUE TITLE
Preview icon selection is inaccurate

### ISSUE THREAD

**Issue by IL2C** [tuberry/color-picker#42]
This issue occurs under both an X11 and Wayland session using GNOME 44.

[Screencast from 2023-04-03 18-16-19.webm](https://user-images.githubusercontent.com/101745538/229581209-2d59f07b-63b1-4a0c-90e2-2a2e02e6734d.webm)

**Comment by tuberry** [comment]
which cursor theme are you using?

**Comment by tuberry** [comment]
I have deactivated the problematic version on E.G.O, you can reinstall from that or from GitHub to see if it fixed.
