### ISSUE TITLE
Semi-transparent square around cursor

### ISSUE THREAD

**Issue by kra-mo** [tuberry/color-picker#44]
On Fedora 38 (GNOME 44.3) Wayland, a semi-transparent square shows up around the preview cursor when picking a color.

![Screenshot from 2023-07-20 18-50-23](https://github.com/tuberry/color-picker/assets/93832451/285076db-a816-48df-a5a3-7e2ed5e44a94)

**Comment by tuberry** [comment]
Already fixed in https://github.com/tuberry/color-picker/commit/c6a3e3d51a741c22d08ef29563a3f30527bed6bd. Please [install from GitHub](https://github.com/tuberry/color-picker#installation) then re-login to see if it works.
