### ISSUE TITLE
Different value sampled depending on preview type

### ISSUE THREAD

**Issue by Sacs** [tuberry/color-picker#45]
I've just installed the extension via https://extensions.gnome.org/ and have found that the value sampled (while using hex) is different for me depending on whether or not I'm using the Label preview or the icon preview.

For example if I go to ebay using chrome and sample the blue b in the logo I get "#0a63cf" and using the icon I get "#0c72ef" even while zoomed in to avoid any weird edge artefacts.

Another example is that if I sample my window colour in my OS, Label is #2c2c2c and Icon is #333333.

I find that the label version is correct based on what I'm doing.

My system info in case it helps is as follows: -

OS: Ubuntu 23.04 x86_64 
Host: XPS 15 9520 
Kernel: 6.2.0-31-generic 
Uptime: 3 days, 8 hours, 34 mins 
Packages: 2410 (dpkg), 15 (flatpak), 33 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1200, 1440x2560, 3440x1440 
DE: GNOME 44.3 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-blue-dark [GTK2/3] 
Icons: Yaru-blue [GTK2/3] 
Terminal: tilix 
CPU: 12th Gen Intel i7-12700H (20) @ 4.600GHz 
GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
GPU: Intel Alder Lake-P 
Memory: 17428MiB / 31758MiB

**Comment by tuberry** [comment]
It is the result of failed filtering of pixels that should not be recolored on the cursor and should be fixed since https://github.com/tuberry/color-picker/commit/c6a3e3d51a741c22d08ef29563a3f30527bed6bd.
You could install it manually, then re-login to see if the two pick the same color:
```shell
git clone --recurse-submodules https://github.com/tuberry/color-picker.git && cd color-picker
git checkout c6a3e3d && meson setup build && meson install -C build
```
