### ISSUE TITLE
NixOS install

### ISSUE THREAD

**Issue by pitamatein** [tuberry/color-picker#46]
GLib.FileError: Failed to open file “/run/current-system/sw/share/gnome-shell/extensions/color-picker@tuberry/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:228:31
  Block@/run/current-system/sw/share/gnome-shell/extensions/color-picker@tuberry/ui.js:13:36
  _buildWidgets@/run/current-system/sw/share/gnome-shell/extensions/color-picker@tuberry/prefs.js:113:21
  ColorPickerPrefs@/run/current-system/sw/share/gnome-shell/extensions/color-picker@tuberry/prefs.js:108:14
  buildPrefsWidget@/run/current-system/sw/share/gnome-shell/extensions/color-picker@tuberry/prefs.js:15:12
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/nix/store/p7rdgmqisryf21x9wg2nawfbjh7c396i-gnome-shell-44.2/share/gnome-shell/.org.gnome.Shell.Extensions-wrapped:7:17

**Comment by tuberry** [comment]
It said the gschemas is not compiled, which should be covered by https://github.com/NixOS/nixpkgs/blob/2f9286912cb215969ece465147badf6d07aa43fe/pkgs/desktops/gnome/extensions/buildGnomeExtension.nix#L40-L46 IIUC. The most straightforward solution is to compile it manually: 
```bash
glib-compile-schemas /run/current-system/sw/share/gnome-shell/extensions/color-picker@tuberry/schemas
```
