### ISSUE TITLE
Quick Settings Toggle

### ISSUE THREAD

**Issue by Anuskuss** [tuberry/color-picker#48]
I think the extension is great but I don't use it nearly enough for it to occupy my precious top bar space. Would you be interested in proving a way to switch from "Icon mode" to "Quick Settings Toggle mode"?

**Comment by tuberry** [comment]
If that's the case, I don't think the [Quick Settings Toggle](https://gitlab.gnome.org/Teams/Design/os-mockups/-/issues/178) area is worth being wasted.  It would be better to either uncheck `Enable systray` and just use the shortcut, or only enable the extension when necessary.
