### ISSUE TITLE
Normalized RGB color option

### ISSUE THREAD

**Issue by jasursadikov** [tuberry/color-picker#49]
## Feature request.
Can you add an option to have an RGB color in format 0-1 where white is (1, 1, 1) and black is (0, 0, 0)?

**Comment by tuberry** [comment]
It will take some effort and time to implement custom/configurable color formats.

Currently, if you are using GNOME 46, you can use the [new DBus interface](https://github.com/tuberry/color-picker?tab=readme-ov-file#dbus) as a temporary workaround:
```bash
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/ColorPicker --method org.gnome.Shell.Extensions.ColorPicker.Pick | grep -oP '<\K[^>]+' | wl-copy -n
```
