### ISSUE TITLE
Does't work well with scaling on Wayland

### ISSUE THREAD

**Issue by vnva** [tuberry/color-picker#50]
![image](https://github.com/tuberry/color-picker/assets/57404657/7edda2ce-2159-4c97-8437-219a293503a5)

**Comment by vnva** [comment]
Works well without scaling
![Screenshot from 2024-03-31 15-00-46](https://github.com/tuberry/color-picker/assets/57404657/f1b1d686-25e7-4c06-8e24-a279714512e3)

**Comment by meybonomme** [comment]
Unfortunately, the problem still exists. Fedora 40, GNOME shell 46, 125% scaling, extension version 41 (from EGO).
Great extension, but completely useless at the moment with fractional scaling.

![pilt](https://github.com/tuberry/color-picker/assets/147217565/794975b1-20b5-48a7-ba90-b07ebf30454b)

**Comment by tuberry** [comment]
This fix has not been uploaded to E.G.O yet, you could install it from [Github](https://github.com/tuberry/color-picker?tab=readme-ov-file#manual) to test if it works.
