### ISSUE TITLE
Error when installing on Ubuntu 24.04

### ISSUE THREAD

**Issue by Matt-Schmitz** [tuberry/color-picker#52]
I get the following error on Ubuntu 24.04.
Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found

**Comment by tuberry** [comment]
Already fixed in https://github.com/tuberry/color-picker/commit/0e042eb1b1f4513dbf0196eb2ed50c4f3e094c5c. Please install it from [GitHub](https://github.com/tuberry/color-picker?tab=readme-ov-file#manual) or wait for review of E.G.O.
