### ISSUE TITLE
Doesn't work after upgrading to Ubuntu 24.04 

### ISSUE THREAD

**Issue by jasiralavibiztripz** [tuberry/color-picker#53]
Doesn't work after upgrading to Ubuntu 24.04 (Gnome shell 46).
Shows the red  error button on gnome extensions page.

I'm getting the below error in a popup when I click on the settings button:
```

Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Json/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by tuberry** [comment]
Already fixed in https://github.com/tuberry/color-picker/commit/0e042eb1b1f4513dbf0196eb2ed50c4f3e094c5c. Please install it from [GitHub](https://github.com/tuberry/color-picker?tab=readme-ov-file#manual) or wait for review of E.G.O.

**Comment by jasiralavibiztripz** [comment]
sudo apt-get update
sudo apt-get install libjson-glib-dev

Running the above in the terminal and then logging out and back in worked for me.
