### ISSUE TITLE
cannot delete colors selected

### ISSUE THREAD

**Issue by sz3bbyla** [tuberry/color-picker#55]
heloo sir, very nice extension for gnome
I would like to clear all colors selected also to have an reset to initial setup because I delete some custom preset give by you initialy by mistake
thank you very much

**Comment by tuberry** [comment]
> I would like to clear all colors selected also to have an reset to initial setup because I delete some custom preset give by you initialy by mistake

You can do all of them by one liner in a terminal:
```bash
dconf reset -f /org/gnome/shell/extensions/color-picker/
```

By the way,

> I would like to clear all colors selected 

If the history were unnecessary, you could turn off the systray indicator and instead invoke it via the shortcut or DBus.

> also to have an reset to initial setup 

I guess very few users need to reset all their settings.

> I delete some custom preset give by you initialy by mistake

The next version might introduce an undo mechanism for delete operations.
