### ISSUE TITLE
Inquiry on how to make extensions

### ISSUE THREAD

**Issue by ghxstbox** [tuberry/color-picker#56]
Hey @tuberry , I am really enjoying your extension. I wanted to ask if you might know of any places to get started on learning how to design an extension, as I went through the extension files and noticed that they are rather complex (you have the extension.js, colors, js, menu.js, etc. files included in the package). Out of curiosity, where did you find the most resources in order to develop your color picker application? Thanks in advance for your time!

**Comment by tuberry** [comment]
I answered a similar question [here](https://github.com/tuberry/extension-list/issues/16#issuecomment-1369450256) that might help you get started.

> noticed that they are rather complex

These codes could be bad practices for [this](https://blog.codinghorror.com/the-best-code-is-no-code-at-all/) :|. If you need some realistic examples for reference, the [official](https://gitlab.gnome.org/GNOME/gnome-shell-extensions) or [Ubuntu‘s](https://github.com/ubuntu/gnome-shell-ubuntu-extensions/blob/4a46a54b90c9439ffbb360f801c74eaa93b5060e/debian/control#L18C1-L21C60) set of extensions might be much more appropriate.

> where did you find the most resources in order to develop your color picker application?

In addition to the resources in that [reply](https://github.com/tuberry/extension-list/issues/16#issuecomment-1369450256), I would say Google, for example, the [color format conversion](http://www.easyrgb.com/en/math.php) comes from online searches. You can also try to use something like [grep.app](https://grep.app/) as a sort of supplement to the official documentation. :)
